### ISSUE TITLE
Importing pre generated end map from java edition

### ISSUE THREAD

**Issue by mclauncherlinux** [wode490390/TheEnd#2]
Hello, I would like to import my pre-generated end map from java edition to this plugin. I use for conversation this:

https://nukkitx.com/resources/java2nukkit-world-converter.252/

how would I do that? I mean importing my converted java edition end to your plugin so that I have some structures at least

thanks for your awesome work

**Comment by wode490390** [comment]
1. Rename the converted world to "the_end"
2. Copy the "the_end" folder to the "worlds" folder of the server
